version: "3.9"
services:
  wembedding:
    image: ghcr.io/ufal/wembedding:tf-2.3.1-gpu-preloaded-staging
    ports:
      - "${PORT_EMB:-8000}:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: ["gpu"]
  udpipe2:
    image: "ghcr.io/ufal/udpipe:2-${U2LANG:-en_ewt}-tf-1.15.4-gpu-staging"
    depends_on:
      - "wembedding"
    ports:
      - "${PORT:-8001}:8001"
    environment:
      - CUDA_VISIBLE_DEVICES=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: ["gpu"]